infer:
  model_checkpoint_path: "/Users/yuriy/Documents/University/ss2019/sonosco/experiments/2019-08-28_12:28:14_default/checkpoints/model_checkpoint.pt"
  audio_path: "" # Audio file to predict on

  sample_rate: 16000 # Sample rate
  window_size: 0.02 # Window size for spectrogram in seconds
  window_stride: 0.01 # Window stride for spectrogram in seconds
  window: 'hamming' # Window type for spectrogram generation

  labels: "ABCDEFGHIJKLMNOPQRSTUVWXYZ' " # labels used by the model

  beam_decoder: False # Turn on beam decoder. otherwise - greedy
  alpha: 0.8
  beam_width: 10
  beta: 1
  cutoff_prob: 1.0
  cutoff_top_n: 40
  lm_path: None # Path to a KenLM binary
  lm_workers: 1
  offsets: False # Returns time offset information
  top_paths: 1

  cuda: True # Use cuda to run model