models:
  - id: 'deepspeech2'
    path: '../pretrained/deepspeech_final.pth'
    decoder: 'greedy'
    name: 'Deep Speech2 (Greedy decoder)'
  - id: 'deepspeech2_beam'
    path: '../pretrained/deepspeech_final.pth'
    decoder: 'beam'
    name: 'Deep Speech2 (Beam decoder)'
  - id: 'deepspeech2_beam_lm'
    path: '../pretrained/deepspeech_final.pth'
    decoder: 'beam'
#    language: '../pretrained/kenlm_bnc_6gram.bin'
    name: 'Deep Speech2 (Beam decoder with LM)'
  - id: 'microsoft'
    external: True
    name: 'Microsoft'


sonosco_home: '~/.sonosco'
audio_database: '~/.sonosco/audio_data'