models:
  - id: 'deepspeech2'
    path: '../pretrained/deepspeech_final.pth'
    name: 'Deep Speech2'
  - id: 'deepspeech2_lm'
    path: '../pretrained/deepspeech_final.pth'
    name: 'Deep Speech2 with LM'
  - id: 'microsoft'
    external: True
    name: 'Microsoft'
