models:
  - id: 'deepspeech2'
    path: '../pretrained/librispeech_pretrained.pth'
    name: 'Deep Speech2'
  - id: 'also_deepspeech2'
    path: '../pretrained/librispeech_pretrained.pth'
    name: 'Other Model'